# serverless.yml

service: personal-site-backend
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2
functions:
  app:
    handler: app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: ANY /
      - http: 'ANY {proxy+}'